### PR TITLE
[9.0][MIG] connector_prestashop: Migrations from Tecnativa.

### PR DESCRIPTION
**Pull request by sergio-teruel**
@simahawk Hi, I am testing the connector i will make PR to your branch ok??. 
The actual branch not create product attributes in Odoo because 'combinations' key in PrestaShop dicctionary is always plural, so I remove from version dicctionary..

### CODE REVIEW

**Comment by simahawk** [comment]
@sergio-teruel ok, thanks! I'll take this "for granted" since we don't have tests yet (I'm working on this).

BTW would you mind update your version for v8 so that we don't have anymore conflicts when we port changes?

**Comment by sergio-teruel** [comment]
@simahawk About v8 version, I first do this changes in v8, then i upgrade it to v9.
One question? I have created a new module to import manufacturers 'connector_prestashop_manufacturers', this module inherits from connector_prestashop and product_manufacturer, but I want mapper a new field by this way:

> @prestashop
> class ProductTemplateMapperManufacturer(TemplateMapper):
>     _model_name = 'prestashop.product.template'

```
direct = (TemplateMapper.direct + [
    (backend_to_m2o('id_manufacturer'), 'prestashop_manufacturer_id'),
])
```

But I do not want a new backend version for this... (This module is for all backend versions). Do you know how to do this?? The documentation says that for this i have to do a new version..

**Comment by simahawk** [comment]
hmm I don't think you need a new backend version for this. Can you add a ref to the docs part?
/cc @guewen

**Comment by guewen** [comment]
@sergio-teruel you have to add a satellite mapper, called by the main one and `replace` it in your module:
- satellite core mapper: https://github.com/OCA/connector-magento/blob/10.0/magentoerpconnect/product.py#L594-L603
- calling the satellite mapper in the main mapper: https://github.com/OCA/connector-magento/blob/10.0/magentoerpconnect/product.py#L436-L439
- replacement of the mapper in the extension addon: https://github.com/OCA/connector-magento/blob/10.0/magentoerpconnect_options_active/product.py

**Comment by sergio-teruel** [comment]
Thanks.. @simahawk and @guewen .. I will try it and take you feedback

**Comment by simahawk** [comment]
@sergio-teruel you could define a generic one for the moment, in the core package

```
@prestashop
class ExtraProductImportMapper(ImportMapper):
    _model_name = 'prestashop.product.product'

    @mapping
    def extras(self, record):
        return {}
```

and override it in depending modules.

**Comment by sergio-teruel** [comment]
@simahawk @guewen Thanks... all ok I have done in this commit https://github.com/OCA/connector-prestashop/pull/22/commits/9e3fcc8444a2ef8a75f95648fbb2fb43c8cf8162 in v8, tomorrow i will do in 9.0.

**Comment by sergio-teruel** [comment]
Cc @pedrobaeza

**Pull request merged**
